name: BuildDeploy

on: 
  push:
    tags: 
      - v1.*
  #[push]

env:
  AZURE_FUNCTIONAPP_NAME: MyBillsApi  # set this to your application's name  
  DOTNET_VERSION: '3.1'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: 'Run Build'
      run: dotnet build src/Api -c Release -o src/Api/output

    - name: 'Run Test'
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=../TestResults/ /p:MergeWith=../TestResults/coverlet.info /p:CoverletOutputFormat=lcov
    
    - name: 'Publish coverage report to coveralls.io'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./tests/TestResults/coverage.info 
        
    - name: 'Install EntityFramework Core'
      run: dotnet tool install --global dotnet-ef

    - name: 'Run Migrations on Azzure SQL database'
      env: 
        SqlConnectionString: ${{ secrets.AZURE_CONNECTION_STRING }}      
      run: dotnet ef database update -p src/Infrastructure -s src/Api --configuration Release
      
    - name: 'Deploy Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: 'src/Api/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
