name: Deploy DotNet project to Azure function app with a Linux environment

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: MyBillsApi  # set this to your application's name  
  DOTNET_VERSION: '3.1'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: 'Build'
      run: dotnet build src/Api -c Release -o src/Api/output

    - name: 'Test'
      run: dotnet test -c Release

    - name: 'Run Migrations on Azzure SQL database'
      env: 
        SqlConnectionString: ${{ secrets.AZURE_CONNECTION_STRING }}
      shell: bash
      run: |              
        dotnet tool install --global dotnet-ef        
        dotnet ef database update -p src/Infrastructure -s src/Api --configuration Release
    - name: 'Deploy Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: 'src/Api/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
