name: Deploy DotNet project to Azure function app with a Linux environment

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: MyBillsApi  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/Api'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      env: 
        SqlConnectionString: ${{ secrets.AZURE_CONNECTION_STRING }}
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        dotnet test --configuration Release
        dotnet tool install --global dotnet-ef
        dotnet ef database update -p ../Infrastructure -s Api.csproj
        popd
    - name: Azure SQL Deploy
      uses: Azure/sql-action@v1
      with:        
        server-name: ${{ secrets.AZURE_SERVER_NAME }}        
        connection-string: ${{ secrets.AZURE_CONNECTION_STRING }}        
        sql-file: migrations.sql
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
